app/Http/routes.php
<?php
Route::get('/', 'HomeController@index');
Route::get('/index', 'HomeController@index');

Route::get('/back', 'HomeController@back');

Route::resource('todos', 'TodosController');
	Route::get('todos/{id}/priorityUp', array('as' => 'priorityUp', 'uses' => 'TodosController@priorityUp'));
	Route::get('todos/{id}/priorityDown', array('as' => 'priorityDown', 'uses' => 'TodosController@priorityDown'));
	Route::get('todos/{id}/done', array('as' => 'done', 'uses' => 'TodosController@done'));
	Route::get('todos/{id}/destroy', array('as' => 'destroy', 'uses' => 'TodosController@destroy'));
Route::resource('tobuys', 'TobuysController');
	Route::get('tobuys/{id}/priorityUp', array('as' => 'priorityUp', 'uses' => 'TobuysController@priorityUp'));
	Route::get('tobuys/{id}/priorityDown', array('as' => 'priorityDown', 'uses' => 'TobuysController@priorityDown'));
	Route::get('tobuys/{id}/done', array('as' => 'done', 'uses' => 'TobuysController@done'));
	Route::get('tobuys/{id}/destroy', array('as' => 'destroy', 'uses' => 'TobuysController@destroy'));

Route::resource('questions', 'QuestionsController');
Route::resource('statements', 'StatementsController');
Route::resource('cbts', 'CbtsController');
Route::resource('todotypes', 'TodoTypesController');
Route::resource('freqs', 'FreqsController');

Route::resource('frontCbts', 'HomeController@frontCbts');
Route::resource('frontQuestions', 'HomeController@frontQuestions');
Route::resource('frontStatements', 'HomeController@frontStatements');
Route::resource('frontTodos', 'HomeController@frontTodos');
Route::resource('frontTobuys', 'HomeController@frontTobuys');

Route::auth();

Route::get('/home', 'HomeController@index');

app/Freq.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Freq extends Model
{

	protected $fillable = [
        'type',
    ];
    
    public function todos()
    {
        return $this->hasMany('App\Todo','freq_id');
    }
}

app/Http/Controllers/FreqsController.php
<?php

namespace App\Http\Controllers;

use DB;
use App\Freq;
use Illuminate\Http\Request;

use App\Http\Requests;

class FreqsController extends Controller
{   
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
    	$freqs = Freq::all();

    	return view('freqs.index', compact('freqs'))
    			->with('title', 'freqs');
    }

    public function create()
    {
        return view('freqs.create')
                ->with('title','freqs');
    }
    public function store(Request $request)
    {
      //  dd($request->all());
        $this->validate($request, [
                'type' => 'required',
        ]);
        $input = $request->all();

        Freq::create($input);

        \Session::flash('flash_message', 'freq successfully added!');

        return redirect()->back();
    }
}

resources/views/freqs/create.blade.php
@extends('layouts.back')

@section('title')
@stop
@section('content')
	<h1>freqs</h1>

		@if(Session::has('flash_message'))
		    <div class="alert alert-success">
		        {{ Session::get('flash_message') }}
		    </div>
		@endif

		@include('partials.alerts.errors')

	{!! Form::open([
	    'route' => 'freqs.store'
	]) !!}

	<div class="form-group">
	    {!! Form::label('type', 'type', ['class' => 'control-label']) !!}
	    {!! Form::text('type', null, ['class' => 'form-control']) !!}
	</div>

	{!! Form::submit('Create New freq', ['class' => 'btn btn-primary']) !!}

	{!! Form::close() !!}
@stop

resources/views/freqs/edit.blade.php
@extends('layouts.back')
@section('title')
freqs
@stop
@section('content')

	@if(Session::has('flash_message'))
	    <div class="alert alert-success">
	        {{ Session::get('flash_message') }}
	    </div>
	@endif
	
	@include('partials.alerts.errors')

<h1>Edit freq </h1>
{!! Form::model($freq, [
    'method' => 'PATCH',
    'route' => ['freqs.update', $freq->id]
]) !!}

<div class="form-group">
    {!! Form::label('freq', 'freq', ['class' => 'control-label']) !!}
    {!! Form::text('freq', null, ['class' => 'form-control']) !!}
</div>


{!! Form::submit('Update freq', ['class' => 'btn btn-primary']) !!}

{!! Form::close() !!}
 <a href="{{ route('freqs.index') }}">Go back to all freqs.</a>


@stop

resources/views/freqs/front.blade.php
@extends('layouts.front')

@section('title')
Statements
@stop
@section('content')
  <script>
  $(function() {
    $( "#dialog" ).dialog({
  width: 400
});
  });
  </script>

<div class="col-md-2">

</div>
<div class="col-md-8">
		<h1>Statements</h1>

				@foreach($statements as $statement)
				    <p>{{ $statement->statement}}</p>
				@endforeach
</div>
<div class="col-md-2">

</div>

<div id="dialog" title="Basic dialog">
  <p>{{ $statements->random()->statement}}</p>
</div>
@stop

resources/views/freqs/index.blade.php
@extends('layouts.back')

@section('title')
@stop
@section('content')

	@if(Session::has('flash_message'))
	    <div class="alert alert-success">
	        {{ Session::get('flash_message') }}
	    </div>
	@endif
<div class="col-md-1">

</div>
<div class="col-md-10">
<h1>freqs</h1>
	<a href="{{ route('freqs.create') }}" class="btn btn-primary">Add New freq</a>
	<table class="table table-striped table-bordered">
		<thead>
		    <tr>
		        <td>todotype</td>
		    </tr>
		</thead>
	@foreach($freqs as $todotype)
	    <tr>
		    <td>{{ $todotype->type }}</td>
    
		    <td>
		        <a href="{{ route('freqs.show', $todotype->id) }}" class="btn btn-info">View freq</a>
		        <a href="{{ route('freqs.edit', $todotype->id) }}" class="btn btn-primary">Edit freq</a>
		    </td>
	    </tr>
	@endforeach
	</table>
</div>
<div class="col-md-1">

</div>
@stop

resources/views/freqs/show.blade.php
@extends('layouts.back')

@section('title')
freqs
@stop
@section('content')
	<b>freq: {{$freq->type}}</b>

@stop